from backend.research.report.renderer import _json_for_script, _md_to_html, generate_visual_report


def test_renderer_returns_standalone_html_with_title_stats_toc_and_sources():
    report = """# A Useful Report

## Overview
A detailed introduction.

### Evidence
The evidence supports the claim.
"""
    html = generate_visual_report(
        question="What did the research find?",
        report_markdown=report,
        sources=[{"url": "https://example.test/source", "title": "Example source"}],
        stats={"Duration": "10s", "Rounds": 2, "Queries": 5, "URLs": 3, "Model": "Groq"},
        session_id="rp-0123456789ab",
    )
    assert html.startswith("<!DOCTYPE html>")
    assert "<title>A Useful Report</title>" in html
    assert "Athena &mdash; Deep Research Report" in html
    assert "Generated by Athena Deep Research" in html
    assert "Duration" in html and "Rounds" in html and "URLs Analyzed" in html
    assert 'href="#overview"' in html
    assert 'href="#evidence"' in html
    assert "Sources (1)" in html
    assert "Example source" in html
    assert "btn-chat-about" not in html
    assert "/api/research/spinoff/" not in html
    assert "/api/research/rp-0123456789ab/hide-image" in html
    assert "/api/research/rp-0123456789ab/unhide-images" in html


def test_renderer_no_session_has_no_session_bound_controls():
    html = generate_visual_report("Question", "## Answer\nText", sources=[], stats={})
    assert "btn-chat-about" not in html
    assert 'id="btn-restore-images"' not in html
    assert "rp-" not in html


def test_renderer_includes_hide_reroll_and_restore_when_images_exist():
    sources = [
        {"url": "https://example.test/a", "title": "A", "image": "https://cdn.example.test/a.jpg"},
        {"url": "https://example.test/b", "title": "B", "image": "https://cdn.example.test/b.jpg"},
    ]
    html = generate_visual_report(
        "Question", "## Section one\nSome text.\n\n## Section two\nMore text.",
        sources=sources, session_id="rp-0123456789ab", hidden_images=["https://cdn.example.test/old.jpg"],
    )
    assert "img-hide-btn" in html
    assert "img-reroll-btn" in html
    assert "Show hidden (1)" in html
    assert "https://cdn.example.test/old.jpg" not in html


def test_renderer_preserves_category_asymmetry_from_source():
    factcheck = generate_visual_report("Question", "## Claim\nText", category="factcheck")
    landscape = generate_visual_report("Question", "## Field\nText", category="landscape")
    assert "category-factcheck" in factcheck
    assert "category-landscape" in landscape
    # Source behavior: factcheck prompt exists, but category CSS defines only landscape.
    assert "body.category-factcheck {" not in factcheck
    assert "body.category-landscape {" in landscape


def test_markdown_content_is_sanitized_before_insertion():
    rendered = _md_to_html(
        '## Safe\n\n<script>alert(1)</script>\n\n'
        '<img src="https://example.test/a.jpg" onerror="alert(1)">\n\n'
        '<a href="javascript:alert(1)">bad link</a>'
    )
    assert "<script" not in rendered.lower()
    assert '<img src="https://example.test/a.jpg" onerror=' not in rendered.lower()
    assert "javascript:" not in rendered.lower()
    assert "Safe" in rendered


def test_renderer_script_json_escapes_script_terminators_and_separators():
    encoded = _json_for_script("</script>\u2028\u2029")
    assert "</script>" not in encoded.lower()
    assert "\\u2028" in encoded
    assert "\\u2029" in encoded
    assert "<\\/script>" in encoded
